# Generated by Django 2.1.5 on 2019-02-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='SOME IMAGE', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_2',
            field=models.CharField(default='SOME TITLE', max_length=255),
        ),
    ]
