# Generated by Django 2.1.5 on 2019-02-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190214_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_2', models.CharField(default='SOME TITLE', max_length=255)),
                ('image', models.ImageField(default='SOME IMAGE', upload_to='images/')),
                ('description', models.CharField(default='SOME STRING', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title_2',
        ),
    ]
